language: go
sudo: true

os:
  - linux
  - osx

go:
  - 1.9.2

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then make coverage && go vet ./...;
    else make test;
    fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

env: TEST_NO_FUSE=1 TEST_VERBOSE=1
